name: dot_attendance
description: DOT ATTENDANCE - Employee attendance management application
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Navigation
  go_router: ^12.1.1
  auto_route: ^7.8.4

  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2

  # Network
  dio: ^5.3.2
  retrofit: ^4.0.3
  pretty_dio_logger: ^1.3.1

  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Authentication & Security
  local_auth: ^2.1.6
  crypto: ^3.0.3

  # UI/UX
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  google_fonts: ^6.1.0

  # Location & Maps
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  google_maps_flutter: ^2.5.0

  # Camera & Image
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  image_cropper: ^5.0.1

  # Date & Time
  intl: ^0.18.1
  timezone: ^0.9.2

  # QR Code
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0

  # Biometric
  local_auth_android: ^1.0.34
  local_auth_ios: ^1.0.16

  # Firebase Services
  firebase_core: ^2.17.0
  firebase_auth: ^4.12.1
  cloud_firestore: ^4.12.2
  firebase_messaging: ^14.7.6
  firebase_functions: ^4.5.6
  firebase_storage: ^11.4.1
  firebase_analytics: ^10.6.1
  firebase_crashlytics: ^3.4.6
  firebase_remote_config: ^4.3.6
  firebase_app_check: ^0.2.1+6
  
  # Push Notifications
  flutter_local_notifications: ^16.1.0
  
  # Google Sign In
  google_sign_in: ^6.1.6

  # Charts & Visualization
  fl_chart: ^0.65.0
  syncfusion_flutter_charts: ^23.2.7
  charts_flutter: ^0.12.0

  # Animations & UI Enhancement
  flutter_animate: ^4.3.0
  flutter_staggered_animations: ^1.1.1
  pull_to_refresh: ^2.0.0
  skeletons: ^0.0.3

  # Export & File Handling
  pdf: ^3.10.7
  excel: ^2.1.0
  path_provider: ^2.1.1
  share_plus: ^7.2.1

  # Utils
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  riverpod_generator: ^2.3.9
  injectable_generator: ^2.4.1
  retrofit_generator: ^8.0.4
  hive_generator: ^2.0.1
  auto_route_generator: ^7.3.2

  # Testing
  mockito: ^5.4.2
  bloc_test: ^9.1.5
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700